language: node_js
node_js:
  - 14

services:
  - docker
  
script:
  - docker --version # print the version for logging
  # Build
  - docker pull trieunv/udagram-frontend:2.1  
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag trieunv/udagram-frontend:2.1 trieunv/udagram-frontend:2.2
  - docker tag udagram-api-feed trieunv/udagram-api-feed:v1
  - docker tag udagram-api-user trieunv/udagram-api-user:v1
  - docker tag reverseproxy trieunv/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   # Push
  - docker push trieunv/udagram-frontend:2.2
  - docker push trieunv/udagram-api-feed:v1
  - docker push trieunv/udagram-api-user:v1
  - docker push trieunv/reverseproxy:v1