# Build
- docker-compose -f docker-compose-build.yaml build --parallel

# Tagging
- docker tag udagram-api-feed patrick55/udagram-api-feed:v1
- docker tag udagram-api-user patrick55/udagram-api-user:v1
- docker tag udagram-frontend patrick55/udagram-frontend:v1
- docker tag reverseproxy patrick55/reverseproxy:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push patrick55/udagram-api-feed:v1
- docker push patrick55/udagram-api-user:v1
- docker push patrick55/udagram-frontend:v1
- docker push patrick55/reverseproxy:v1