language: minimal

services: docker

before_install:
  - docker -v && docker-compose -v

script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed transytai12a1/udagram-api-feed:v3
  - docker tag udagram-api-user transytai12a1/udagram-api-user:v3
  - docker tag udagram-frontend transytai12a1/udagram-frontend:v3
  - docker tag reverseproxy transytai12a1/reverseproxy:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push transytai12a1/udagram-api-feed:v3
  - docker push transytai12a1/udagram-api-user:v3
  - docker push transytai12a1/udagram-frontend:v3
  - docker push transytai12a1/reverseproxy:v6
