language: node_js
node_js:
  - 12

services:
  - docker

# Scripts to be run such as test
before_script:
  - echo "travis run is about to start"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend trinhho2907/udagram-frontend:v1
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed trinhho2907/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user trinhho2907/udagram-api-user:v1 
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy trinhho2907/reverseproxy:v1

after_script:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push trinhho2907/udagram-api-feed:v1
  - docker push trinhho2907/udagram-api-user:v1
  - docker push trinhho2907/udagram-frontend:v1
  - docker push trinhho2907/reverseproxy:v1