sudo: required

language: ruby

services:
  - docker

before_install:
  - echo "Testing Docker Hub credentials"
  - echo "$DOCKER_HUB_USER"
  - echo "env varaibles are set"

script:
  - docker ps -a

after_success:
  # LOGIN TO DOCKER HUB
  - docker login -e=$DOCKER_HUB_EMAIL -u=$DOCKER_HUB_USER -p=$DOCKER_HUB_SECRET
  # BUILD IMAGES USING DOCKER-COMPOSE
  - docker-compose -f docker-compose-build.yaml build --parallel
  # TAG THE IMAGES
  - docker tag udagram-api-feed ndzib/udagram-api-feed:v1
  - docker tag udagram-api-user ndzib/udagram-api-user:v1
  - docker tag udagram-frontend ndzib/udagram-frontend:v1
  - docker tag reverseproxy ndzib/reverseproxy:v1
  # PUSH IMAGES TO DOCKER HUB
  - docker push ndzib/udagram-api-feed:v1
  - docker push ndzib/udagram-api-user:v1
  - docker push ndzib/udagram-frontend:v1
  - docker push ndzib/reverseproxy:v1
