language: node_js
node_js:
  - 16

services:
  - docker

# Use either `docker-compose` or individual `docker build` commands
# Build
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed hm88/udagram-api-feed:v1
  - docker tag udagram-api-user hm88/udagram-api-user:v1
  - docker tag udagram-frontend hm88/udagram-frontend:v1
  - docker tag reverseproxy hm88/reverseproxy:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hm88/udagram-api-feed:v1
  - docker push hm88/udagram-api-user:v1
  - docker push hm88/udagram-frontend:v1
  - docker push hm88/reverseproxy:v1
