language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
        # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
        # Tagging
  - docker tag udagram-api-feed osaladev/udagram-api-feed:latest
  - docker tag udagram-api-user osaladev/udagram-api-user:latest
  - docker tag udagram-frontend osaladev/udagram-frontend:latest
  - docker tag udagram-reverseproxy osaladev/udagram-reverseproxy:latest

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push osaladev/udagram-api-feed:latest
  - docker push osaladev/udagram-api-user:latest
  - docker push osaladev/udagram-frontend:latest
  - docker push osaladev/udagram-reverseproxy:latest
