language: node_js
node_js:
  - 16.14.0

services: 
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.29.2

install:  
  - echo "Nothing to install"

before_script:
  - docker --version # print the version for logging
  - docker-compose --version # print the version for logging
  # - docker-compose -f docker-compose-build.yaml build --parallel

script: 
  # Build images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  # Tag images
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user
  - docker tag reverseproxy $DOCKER_USERNAME/reverseproxy
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend
  

after_success: 
  # Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push images to docker hub
  - docker push $DOCKER_USERNAME/udagram-api-feed
  - docker push $DOCKER_USERNAME/udagram-api-user
  - docker push $DOCKER_USERNAME/reverseproxy
  - docker push $DOCKER_USERNAME/udagram-frontend