# Build images
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./reverseproxy

# Tag images
- docker tag udagram-api-feed zeyadmobarez/udagram-api-feed:v4a
- docker tag udagram-api-user zeyadmobarez/udagram-api-user:v4a
- docker tag udagram-frontend zeyadmobarez/udagram-frontend:v4a
- docker tag reverseproxy zeyadmobarez/reverseproxy:local

# Login to DockerHub and push images
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push zeyadmobarez/udagram-api-feed:v4a
- docker push zeyadmobarez/udagram-api-user:v4a
- docker push zeyadmobarez/udagram-frontend:v4a
- docker push zeyadmobarez/reverseproxy:local
