
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed

# Tagging
- docker tag udagram-api-feed zeyadmobarez/udagram-api-feed:v4a

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push zeyadmobarez/udagram-api-feed:v4a



# for udagram-api-user

- docker build -t udagram-api-user ./udagram-api-user

# Tagging
- docker tag udagram-api-user zeyadmobarez/udagram-api-user:v4a

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push zeyadmobarez/udagram-api-user:v4a



## for udagram frontend 

- docker build -t udagram-frontend ./udagram-frontend

# Tagging
- docker tag udagram-frontend zeyadmobarez/udagram-frontend:local
  
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push zeyadmobarez/udagram-frontend:local



# for reverseproxy nginx

- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging
- docker tag udagram-reverseproxy zeyadmobarez/udagram-reverseproxy:v4a

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push zeyadmobarez/udagram-reverseproxy:v4a
