language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the docker version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed zeyadmobarez/udagram-api-feed:v4a

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user zeyadmobarez/udagram-api-user:v4a

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend zeyadmobarez/udagram-frontend:local

  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy zeyadmobarez/reverseproxy:v4a

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zeyadmobarez/udagram-api-feed:v4a
  - docker push zeyadmobarez/udagram-api-user:v4a
  - docker push zeyadmobarez/udagram-frontend:local
  - docker push zeyadmobarez/reverseproxy:v4a