kind: Secrete
apiVersion: v1
metadata:
  name: aws-secrete
type: Opaque
data:
  aws_access_key_id: QUtJQTI3NlZJUTZWWkhJQlJTWUQ=
  aws_secret_access_key: eTR5dGo1NzRuT2owdHpKTnd4dnVFWWFVQjJaZ1pkMGlISzRya0VwUw==
