apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: sharonibejih/udagram-api-feed:v1
          ports:
          - containerPort: 8080 # Exposed port in backend-feed dockerfile
          envFrom:
            - configMapRef:
                name: udagram-config
            - secretRef:
                name: udagramdb-secrets
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: udagram-aws-config
      volumes:
        - name: udagram-aws-config
          configMap:
            name: udagram-aws-config

