apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  selector: # this is the deployment name the service should speak to.
    app: backend-user
  ports:
    - protocol: TCP
      port: 8080 # entrance port -> what nginx is listening to
      targetPort: 8080 # Exposed Port in the backend-user DockerFile