version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8888:8888
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgresAbc111" 
      POSTGRES_DB: "postgres" 
      POSTGRES_HOST: "postgres.cohefwz5riff.us-east-1.rds.amazonaws.com"
      AWS_REGION: "us-east-1" 
      AWS_PROFILE: "serverless-admin"
      AWS_BUCKET: "c2-udacity"
      JWT_SECRET: "testing"
      PORT: 8888
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgresAbc111" 
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "postgres.cohefwz5riff.us-east-1.rds.amazonaws.com"
      AWS_REGION: "us-east-1"
      AWS_PROFILE: "serverless-admin"
      AWS_BUCKET: "c2-udacity"
      JWT_SECRET: "testing"
      PORT: 8888
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"