apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector: # this is the deployment name the service should speak to.
    app: frontend
  ports:
    - protocol: TCP
      port: 8100 # can be any port. This is the very first entry port of a user, e.g: localhost:8100
      targetPort: 8080 # The entry port above will be redirected to the Docker Container Port (as used in frontend-deployment.yaml)