apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - image: transytai12a1/udagram-frontend:v1
        name: udagram-frontend
        ports:
        - containerPort: 8100
