apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - image: transytai12a1/reverseproxy:v3
        name: udagram-reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
