apiVersion: v1
kind: Service
metadata:
  labels:
      app: api-user
  name: api-user
  namespace: default
spec:
  selector:
    app: api-user
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080