apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-user
  name: api-user
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
      - image: zeyadahmed/udagram-api-user:v4a
        name: api-user
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        volumeMounts:
          - name: aws-secret
            mountPath: /root/.aws/
            readOnly: true        
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret 