apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  selector:
    matchLabels:
      service: api-feed
  replicas: 3
  template:
    metadata:
      labels:
        service: api-feed
    spec:
      containers:
      - image: zeyadmobarez/udagram-api-feed:v4a
        name: api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - name: aws-secret
          mountPath: /root/.aws
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret