version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    working_directory: /cd0354-monolith-to-microservices-project
    docker:
      - image: 'docker:stable'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: |
            docker --version
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed thienntn1/udagram-api-feed

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user thienntn1/udagram-api-user

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend thienntn1/udagram-frontend

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy thienntn1/udagram-reverseproxy
      - deploy:
          name: Push application Docker images
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker push thienntn1/udagram-api-feed:latest
            docker push thienntn1/udagram-api-user:latest
            docker push thienntn1/udagram-frontend:latest
            docker push thienntn1/udagram-reverseproxy:latest