version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tatchumnono/*
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  publishLatestToHub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build . -t udagram-api-feed -f .././udagram-api-feed
            docker push udagram-api-feed:v1
            docker build . -t udagram-api-user -f .././udagram-api-user
            docker push udagram-api-user:v1
            docker build . -t udagram-frontend -f .././udagram-frontend 
            docker push udagram-frontend:v1
            docker build . -t udagram-reverseproxy -f .././udagram-reverseproxy
            docker push udagram-reverseproxy:v1
workflows:
  version: 2
  build-master:
    jobs:
      - publishLatestToHub
