version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo install nodejs

            echo "--------- The images is Building ------------"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed copa-cabana/udagram-api-feed:v3

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user copa-cabana/udagram-api-user:v3
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend copa-cabana/udagram-frontend:v3

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy copa-cabana/udagram-reverseproxy:v3

            echo "-------- All images succesfully built----------"

            echo " ------- login in to hub--------"

            docker login -u copa-cabana -p $DOCKERPASS

            echo "-------------- Pushing images to dockerhub-------"

            docker push copa-cabana/udagram-api-feed:v3
            docker push copa-cabana/udagram-api-user:v3
            docker push copa-cabana/udagram-frontend:v3
            docker push copa-cabana/udagram-reverseproxy:v3
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]

