apiVersion: v1
kind: Service
metadata:
  name: forntend
  labels:
    run: frontend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: frontend
  
