name: Build and push Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and tag Docker images
        run: |
          docker build -t udagram-api-feed ./udagram-api-feed
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t udagram-frontend ./udagram-frontend
          docker build -t reverseproxy ./reverseproxy
          
          docker tag udagram-api-feed zeyadmobarez/udagram-api-feed:v4
          docker tag udagram-api-user zeyadmobarez/udagram-api-user:v4
          docker tag udagram-frontend zeyadmobarez/udagram-frontend:v4
          docker tag reverseproxy zeyadmobarez/reverseproxy:local1
          
      - name: Login to DockerHub and push images
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker images
        run: |
          docker push zeyadmobarez/udagram-api-feed:v4
          docker push zeyadmobarez/udagram-api-user:v4
          docker push zeyadmobarez/udagram-frontend:v4
          docker push zeyadmobarez/reverseproxy:local1