jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Build and tag Docker images
        run: |
          docker build -t udagram-api-feed ./udagram-api-feed
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t udagram-frontend ./udagram-frontend
          docker build -t reverseproxy ./reverseproxy
          
          docker tag udagram-api-feed zeyadmobarez/udagram-api-feed:v4a
          docker tag udagram-api-user zeyadmobarez/udagram-api-user:v4a
          docker tag udagram-frontend zeyadmobarez/udagram-frontend:v4a
          docker tag reverseproxy zeyadmobarez/reverseproxy:local
          
      - name: Login to DockerHub and push images
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker images
        run: |
          docker push zeyadmobarez/udagram-api-feed:v4
          docker push zeyadmobarez/udagram-api-user:v4
          docker push zeyadmobarez/udagram-frontend:v4
          docker push zeyadmobarez/reverseproxy:local1
